## Summary
### single nutrient perturbation

- SNPv1 (base line pmg_wt_77;pmg_wt_78)

    raplace C course or N source
    
    118 samples - 59 conditions, 2 replicates each

    fixed: M9 + NH4Cl + pH7 + 37 degrees C + aerobic

    - **carbon_df**: \<C source\> + NH4Cl, 82 samples - 41 conditions, 2 replicates each
    - **nitrogen_df**: Glucose + \<N source\>, 38 samples - 19 conditions, 2 replicates each

- SNPv2 (base line pmg_wt_145;pmg_wt_146)

    Glucose_NH4Cl and add extra supplement
    
    - **sumplement_df**: Glucose_NH4Cl + supplement, 204 samples - 102 conditions, 2 replicates each

### Antibiotic exposure

Glucose + NH4Cl
- AntibiotICA

    **abx_media_df** (4 Antibiotics + control) * (3 mediums)
- pilot-AntibiotICA

    **abx_time_df**: antibiotics + timeline

### sationary-TRN

C-, N-, S- starvation/growth-state dataset. 
    
How the system reorgnizes when it turns to stationary phase from exponential growth

---
## Further analysis

### MiniSpan

aerobic/anaeribic

### OxyR ALE

with/without H2O2, oxidative stress response

### Nac/NtrC

nitrogen environment. Rebuilding the nitrogen regulatory network of NrtC and Nac. Cytosin, cytidine adn glutamine as N-source

### Cra/Crp

How they regulate the central carbon metabolism

In [2]:
import numpy as np
import pandas as pd

In [11]:
samples = pd.read_csv("precise_mg1655-sample_table.csv", header=0)
tpm = pd.read_csv("precise_mg1655-log_tpm.csv", header=0)

In [12]:
def filter_tpm_by_metadata(filtered_metadata, tpm_table = tpm):
    """
    Filter TPM expression table using unique_identifier
    from a filtered metadata dataframe.

    Parameters
    ----------
    filtered_metadata : pd.DataFrame
        Filtered sample metadata containing unique_identifier.

    tpm_table : pd.DataFrame
        Gene expression table:
        rows = genes
        columns = sample unique_identifiers.

    Returns
    -------
    pd.DataFrame
        TPM table containing gene_id + selected samples.
    """

    # Get filtered sample IDs
    sample_ids = (filtered_metadata["unique_identifier"].tolist())

    # Keep only IDs that actually exist in TPM table
    valid_ids = [
        sample_id
        for sample_id in sample_ids
        if sample_id in tpm_table.columns
    ]

    # Check missing IDs
    missing_ids = [
        sample_id
        for sample_id in sample_ids
        if sample_id not in tpm_table.columns
    ]

    if missing_ids:
        print("Warning: IDs not found in TPM table:")
        print(missing_ids)

    # gene_id + selected samples
    filtered_tpm = tpm_table[["gene_id"] + valid_ids].copy()
    return filtered_tpm

In [4]:
# SNPv1
# C source variation, N source NH4Cl fixed
# condition: <C Source>_NH4Cl
# reference_condition_identifier: pmg_wt_77;pmg_wt_78

carbon_df = samples[
    (samples["project"] == "SNPv1")
    & (samples["condition"].str.endswith("_NH4Cl", na=False))
].copy()
carbon_df.head() # 82 samples - 41 conditions, 2 replicates each

,unique_identifier,project_name,condition,replicate_id,reference_condition_identifier,reference_strain,deleted_genes,mutated_genes,overexpressed_genes,perturbed_gene_ids,...,Trace Element Mixture,Run,SRX,n_replicates,passed_pct_reads_mapped,passed_number_replicates,passed_similar_replicates,Antibiotic for selection,enriched_condition,enriched_project
2,pmg_wt_100,single_nutrient_perturbation,Uridine_NH4Cl,2,pmg_wt_77;pmg_wt_78,MG1655,NaN,NaN,NaN,NaN,...,Sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,pmg_wt_107,single_nutrient_perturbation,D-Trehalose_NH4Cl,1,pmg_wt_77;pmg_wt_78,MG1655,NaN,NaN,NaN,NaN,...,Sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,pmg_wt_108,single_nutrient_perturbation,D-Trehalose_NH4Cl,2,pmg_wt_77;pmg_wt_78,MG1655,NaN,NaN,NaN,NaN,...,Sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,pmg_wt_125,single_nutrient_perturbation,D-Mannose_NH4Cl,1,pmg_wt_77;pmg_wt_78,MG1655,NaN,NaN,NaN,NaN,...,Sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,pmg_wt_126,single_nutrient_perturbation,D-Mannose_NH4Cl,2,pmg_wt_77;pmg_wt_78,MG1655,NaN,NaN,NaN,NaN,...,Sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# e.g. the tpm table for carbon_df
carbon_tpm = filter_tpm_by_metadata(carbon_df, tpm)
carbon_tpm.head() # rows = genes, columns = 82 samples

,gene_id,pmg_wt_100,pmg_wt_107,pmg_wt_108,pmg_wt_125,pmg_wt_126,pmg_wt_141,pmg_wt_142,pmg_wt_143,pmg_wt_144,...,pmg_wt_90,pmg_wt_91,pmg_wt_92,pmg_wt_93,pmg_wt_94,pmg_wt_95,pmg_wt_96,pmg_wt_97,pmg_wt_98,pmg_wt_99
0,b0001,0.722802,1.090242,1.130414,1.860347,2.260856,-0.990012,-0.877302,1.217422,1.288113,...,-1.984772,-2.815976,-3.011560,-2.576984,-1.262916,1.347708,1.841094,-0.552674,-1.566595,1.227660
1,b0002,-0.822170,-0.955810,-1.223776,-1.001151,-1.001738,-0.276547,-0.114908,-0.452704,-0.855671,...,-0.262290,-0.522540,-0.558576,-2.008627,-2.383164,-0.117049,-0.147349,-1.088351,-0.983296,-0.554786
2,b0003,0.091438,-0.803884,-1.207059,-0.791466,-0.815086,0.420163,0.490753,-0.188748,-0.720093,...,-0.915576,-0.092215,-0.158409,-1.713275,-1.931230,0.119124,0.021417,-0.765254,-0.525073,0.147829
3,b0004,-0.045651,-0.741174,-0.888425,-0.788650,-0.796482,0.267219,0.346992,-0.119051,-0.609777,...,-0.640566,0.171979,0.055813,-1.294275,-1.648703,0.012734,-0.067448,-0.590740,-0.351376,-0.105335
4,b0005,-0.470824,-0.298003,-0.370604,-0.683099,-0.937261,-0.473663,-1.197339,-0.562813,-0.627894,...,-0.601563,-0.125883,-0.228694,-1.567951,-1.622031,-0.906826,-0.701478,-1.423720,-1.224787,-0.746430

In [5]:
#SNPv1
# N source variation, C source glucose fixed
# condition: Glucose_<N Source>
# reference_condition_identifier: pmg_wt_77;pmg_wt_78

nitrogen_df = samples[
    (samples["project"] == "SNPv1")
    & (samples["condition"].str.startswith(("Glucose_", "D-Glucose_"), na=False))
].copy()
nitrogen_df.head() # 38 samples - 19 conditions, 2 replicates each

,unique_identifier,project_name,condition,replicate_id,reference_condition_identifier,reference_strain,deleted_genes,mutated_genes,overexpressed_genes,perturbed_gene_ids,...,Trace Element Mixture,Run,SRX,n_replicates,passed_pct_reads_mapped,passed_number_replicates,passed_similar_replicates,Antibiotic for selection,enriched_condition,enriched_project
3,pmg_wt_101,single_nutrient_perturbation,Glucose_L-Ornithine,1,pmg_wt_77;pmg_wt_78,MG1655,NaN,NaN,NaN,NaN,...,Sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,pmg_wt_102,single_nutrient_perturbation,Glucose_L-Ornithine,2,pmg_wt_77;pmg_wt_78,MG1655,NaN,NaN,NaN,NaN,...,Sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,pmg_wt_103,single_nutrient_perturbation,Glucose_Putrescine,1,pmg_wt_77;pmg_wt_78,MG1655,NaN,NaN,NaN,NaN,...,Sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,pmg_wt_104,single_nutrient_perturbation,Glucose_Putrescine,2,pmg_wt_77;pmg_wt_78,MG1655,NaN,NaN,NaN,NaN,...,Sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,pmg_wt_105,single_nutrient_perturbation,Glucose_N-Acetyl-Neuraminic_acid,1,pmg_wt_77;pmg_wt_78,MG1655,NaN,NaN,NaN,NaN,...,Sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#SNPv2
supplement_df = samples[(samples["project"] == "SNPv2")].copy()
supplement_df.head() # 204 samples - 102 conditions, 2 replicates each

,unique_identifier,project_name,condition,replicate_id,reference_condition_identifier,reference_strain,deleted_genes,mutated_genes,overexpressed_genes,perturbed_gene_ids,...,Trace Element Mixture,Run,SRX,n_replicates,passed_pct_reads_mapped,passed_number_replicates,passed_similar_replicates,Antibiotic for selection,enriched_condition,enriched_project
51,pmg_wt_145,single_nutrient_perturbation,Glucose_NH4Cl,1,pmg_wt_145;pmg_wt_146,MG1655,NaN,NaN,NaN,NaN,...,Sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,pmg_wt_146,single_nutrient_perturbation,Glucose_NH4Cl,2,pmg_wt_145;pmg_wt_146,MG1655,NaN,NaN,NaN,NaN,...,Sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,pmg_wt_147,single_nutrient_perturbation,Supp_Histidine_(2mM),1,pmg_wt_145;pmg_wt_146,MG1655,NaN,NaN,NaN,NaN,...,Sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,pmg_wt_148,single_nutrient_perturbation,Supp_Histidine_(2mM),2,pmg_wt_145;pmg_wt_146,MG1655,NaN,NaN,NaN,NaN,...,Sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,pmg_wt_149,single_nutrient_perturbation,Supp_D-Gluconic acid_(10mM),1,pmg_wt_145;pmg_wt_146,MG1655,NaN,NaN,NaN,NaN,...,Sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Antibiotic exposure
# project: AntibiotICA
# Antibiotics(4+1): meropenem(mero), trimethoprim-sulfamethoxazole(trisulf), ceftriaxone(cef), ciprofloxacin(cipro), control(ctrl)
# Mediums(3): M9(m9), RPMI+10%LB(rpmi), CAMHB(camhb)

abx_media_df = samples[(samples["project_name"] == "AntibiotICA")].copy()
# abx_media_df  30 samples - 15 conditions, 2 replicates each

# Query (medium_antibtiotic), e.g. m9_mero, rpmi_trisulf, camhb_ctrl
abx_media_df[abx_media_df["condition"].str.startswith("m9_", na=False)].copy()

abx_media_df[abx_media_df["condition"].str.endswith("_ctrl", na=False)].copy()

,unique_identifier,project_name,condition,replicate_id,reference_condition_identifier,reference_strain,deleted_genes,mutated_genes,overexpressed_genes,perturbed_gene_ids,...,Trace Element Mixture,Run,SRX,n_replicates,passed_pct_reads_mapped,passed_number_replicates,passed_similar_replicates,Antibiotic for selection,enriched_condition,enriched_project
302,pmg_wt_371,AntibiotICA,m9_ctrl,1,pmg_wt_371;pmg_wt_372,MG1655,NaN,NaN,NaN,NaN,...,sauer trace element mixture,SRR12820309,SRX9288042,2.0,True,True,True,NaN,[object Object],[object Object]
303,pmg_wt_372,AntibiotICA,m9_ctrl,2,pmg_wt_371;pmg_wt_372,MG1655,NaN,NaN,NaN,NaN,...,sauer trace element mixture,SRR12820310,SRX9288043,2.0,True,True,True,NaN,[object Object],NaN
304,pmg_wt_373,AntibiotICA,rpmi_ctrl,1,pmg_wt_371;pmg_wt_372,MG1655,NaN,NaN,NaN,NaN,...,NaN,SRR12820311,SRX9288044,2.0,True,True,True,NaN,[object Object],NaN
305,pmg_wt_374,AntibiotICA,rpmi_ctrl,2,pmg_wt_371;pmg_wt_372,MG1655,NaN,NaN,NaN,NaN,...,NaN,SRR12820312,SRX9288045,2.0,True,True,True,NaN,[object Object],NaN
306,pmg_wt_375,AntibiotICA,camhb_ctrl,1,pmg_wt_371;pmg_wt_372,MG1655,NaN,NaN,NaN,NaN,...,NaN,SRR12820313,SRX9288046,2.0,False,True,True,NaN,[object Object],NaN
307,pmg_wt_376,AntibiotICA,camhb_ctrl,2,pmg_wt_371;pmg_wt_372,MG1655,NaN,NaN,NaN,NaN,...,NaN,SRR12820314,SRX9288047,2.0,True,True,True,NaN,[object Object],NaN

In [8]:
# Antibiotic exposure
# project: pilot-AntibiotICA, Antibiotics in timeline
# Antibiotics: Ampicillin(amp_1), Ciprofloxacin(cipro)
# time: 0, 1.5, 3.5, 7.5, 15, 30 min
# dose:
    # amp: 16 ug/ml, 4 ug/ml,
    # cipro: 0.016 ug/ml (with different sequencing kit vayr)

abx_time_df = samples[(samples["project_name"] == "pilot-antibiotICA")].copy()
abx_time_df.head() # 40 samples - 20 conditions, 2 replicates each
# condition: <antibiotic>_(<dose>/<kit>)__<time>, e.g. amp_1_16_t0, cipro_t30

,unique_identifier,project_name,condition,replicate_id,reference_condition_identifier,reference_strain,deleted_genes,mutated_genes,overexpressed_genes,perturbed_gene_ids,...,Trace Element Mixture,Run,SRX,n_replicates,passed_pct_reads_mapped,passed_number_replicates,passed_similar_replicates,Antibiotic for selection,enriched_condition,enriched_project
340,pmg_wt_405,pilot-antibiotICA,amp_1_16_t0,1,pmg_wt_405;pmg_wt_406,MG1655,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
341,pmg_wt_406,pilot-antibiotICA,amp_1_16_t0,2,pmg_wt_405;pmg_wt_406,MG1655,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342,pmg_wt_407,pilot-antibiotICA,amp_1_16_t1_5,1,pmg_wt_405;pmg_wt_406,MG1655,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,pmg_wt_408,pilot-antibiotICA,amp_1_16_t1_5,2,pmg_wt_405;pmg_wt_406,MG1655,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,pmg_wt_409,pilot-antibiotICA,amp_1_16_t15,1,pmg_wt_405;pmg_wt_406,MG1655,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# stationary-TRN
# How is the TRN reorgnized when E. coli enters the stationary phase due to the depletion of different nutrients?
# C/N/S starvation, timeline: C3, C4, C5, N3, N4, N5, N8, N12, S4, S8, S12

stationary_trn_df = samples[(samples["project_name"] == "stationary-TRN")].copy()
stationary_trn_df.head() # 22 samples - 11 conditions, 2 replic

,unique_identifier,project_name,condition,replicate_id,reference_condition_identifier,reference_strain,deleted_genes,mutated_genes,overexpressed_genes,perturbed_gene_ids,...,Trace Element Mixture,Run,SRX,n_replicates,passed_pct_reads_mapped,passed_number_replicates,passed_similar_replicates,Antibiotic for selection,enriched_condition,enriched_project
277,pmg_wt_349,stationary-TRN,stationary_C_3h,1,pmg_wt_349;pmg_wt_350,MG1655,NaN,NaN,NaN,NaN,...,sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[object Object],[object Object]
279,pmg_wt_350,stationary-TRN,stationary_C_3h,2,pmg_wt_349;pmg_wt_350,MG1655,NaN,NaN,NaN,NaN,...,sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[object Object],NaN
280,pmg_wt_351,stationary-TRN,stationary_N_3h,1,pmg_wt_349;pmg_wt_350,MG1655,NaN,NaN,NaN,NaN,...,sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[object Object],NaN
281,pmg_wt_352,stationary-TRN,stationary_N_3h,2,pmg_wt_349;pmg_wt_350,MG1655,NaN,NaN,NaN,NaN,...,sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[object Object],NaN
282,pmg_wt_353,stationary-TRN,stationary_C_4h,1,pmg_wt_349;pmg_wt_350,MG1655,NaN,NaN,NaN,NaN,...,sauer trace element mixture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[object Object],NaN